#!/usr/bin/env bash
#
# Install the configure file including shell configure and vim configure

vimcdoc_url="https://sourceforge.net/projects/vimcdoc/files/vimcdoc/vimcdoc-2.1.0.tar.gz/download"

this_script_dir=$(cd "$(dirname "$0")"; pwd)

function usage() {
  echo "install dotfiles"
  echo ""
  echo "USAGE:"
  echo "install [-h] [-v] [-n] [-b <backup_dir>] [-i <install_dir>]"
  echo "    -h: echo this documents"
  echo "    -v: print details when install"
  echo "    -n: not backup file in -b"
  echo "    -b: backup dir, default is \$HOME/.backups"
  echo "    -i: install dir, default is \$HOME"
  echo ""
  echo "-----------------------------------------------------------"
  echo "                         by m(https://menghuu.github.com)"
}

while getopts "nvb:i:hs:" opt; do
  case $opt in
    n)
      not_backup=true
      ;;
    v)
      verbose=true
      ;;
    b)
      backup_dir=${OPTARG}
      ;;
    i)
      install_dir=${OPTARG}
      ;;
    s)
      source_dir=${OPTARG}
      ;;
    h)
      usage
      exit 0
      ;;
    esac
done

verbose=${verbose:-false}
not_backup=${not_backup:-false}
debug=${debug:-false}

install_dir=${install_dir:-"$HOME"}
backup_dir=${backup_dir:-"${install_dir}/.backups"}
source_dir=${source_dir:-"${this_script_dir}"}

backup_dir=$(realpath ${backup_dir})
install_dir=$(realpath ${install_dir})
source_dir=$(realpath ${source_dir})

rm -fr ${backup_dir}

if ${verbose}; then
   echo backup_dir is: "${backup_dir}"
   echo verbose is: "${verbose}"
   echo not_backup is: "${not_backup}"
   echo install_dir is: "${install_dir}"
   echo source_dir is: "${source_dir}"
   echo "========================="
fi

function append_line() {
  set -e

  local update line file pat lno
  update="$1"
  line="$2"
  file="$3"
  pat="${4:-}"
  lno=""

  echo "Update $file:"
  echo "  - $line"
  if [ -f "$file" ]; then
    if [ $# -lt 4 ]; then
      lno=$(\grep -nF "$line" "$file" | sed 's/:.*//' | tr '\n' ' ')
    else
      lno=$(\grep -nF "$pat" "$file" | sed 's/:.*//' | tr '\n' ' ')
    fi
  fi
  if [ -n "$lno" ]; then
    echo "    - Already exists: line #$lno"
  else
    if [ $update -eq 1 ]; then
      [ -f "$file" ] && echo >> "$file"
      echo "$line" >> "$file"
      echo "    + Added"
    else
      echo "    ~ Skipped"
    fi
  fi
  echo
  set +e
}

function hm_backup() {
  # test if a link
  local from_path="$1"
  local file_name="$(basename ${from_path})"
  local dest_dir="$2"
  local dest_path="${dest_dir}/${file_name}"
  local verbose="$3"
  if [ ! -e "${from_path}" ]; then
    #${verbose} && echo "    ${from_path} not exist" && true
    true
  elif [ -L "${from_path}" ]; then
    ${verbose} && echo "    back link ${from_path} to ${dest_path}"
    real_path="$(realpath ${from_path})"
    ln -sf ${real_path} "${dest_path}"
  else
    "${verbose}" && echo "    mv file/dir ${from_path} to ${dest_path}"
    mv -f "${from_path}" "${dest_path}"
  fi
}

function elementIn() {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

function hm_link(){
  local base_dir dest_dir backup_dir not_backup verbose exclude_names
  local from_path backup_path dest_path
  base_dir=${1}
  dest_dir=${2}
  backup_dir=${3}
  not_backup=${4}
  verbose=${5}
  shift 5
  exclude_names="$@"
  [ ! -e ${base_dir} ] && mkdir -p ${base_dir}
  [ ! -e ${dest_dir} ] && mkdir -p ${dest_dir}
  [ ! -e ${backup_dir} ] && mkdir -p ${backup_dir}
  for file_name in $(ls -1A "${base_dir}"); do
    if elementIn "${file_name}" ${exclude_names[@]}; then
      ${verbose} && echo "  ${file_name} is excluded"
      continue
    fi
    echo "  do with ${file_name}"
    from_path="${base_dir}/${file_name}"
    backup_path="${backup_dir}/${file_name}"
    dest_path="${dest_dir}/${file_name}"
    if ! "${not_backup}"; then
      hm_backup "${dest_path}" "${backup_dir}" ${verbose}
      #echo "  backup ${dest_path} success"
    fi
    ${verbose} && echo -e "    $(tput setaf 2)link ${dest_path} --> ${from_path}\tsuccess$(tput sgr 0)"
    ln -s -f "${from_path}" "${dest_path}"
  done
}

#===============================================================================
echo "$(tput setaf 3)link file in ${source_dir}/dotfiles excluding .config$(tput sgr 0)"
hm_link "${source_dir}/dotfiles" "${install_dir}" "${backup_dir}" \
    ${not_backup} ${verbose} ".config" ".local"


#===============================================================================
echo "$(tput setaf 3)link file in ${source_dir}/dotfiles/.config$(tput sgr 0)"
hm_link "${source_dir}/dotfiles/.config" "${install_dir}/.config" \
    "${backup_dir}/.config" ${not_backup} ${verbose}


#===============================================================================
echo "$(tput setaf 3)install vim chinese document$(tput sgr 0)"
tmp_dir=$(mktemp -d)
install_vimcdoc=${install_vimcdoc:-true}

${verbose} && echo "mkdir temp dir ${tmp_dir}"

${install_vimcdoc} && \
(
  (command -v curl > /dev/null \
      && (${verbose} && echo "$(tput setaf 3)find curl, using curl to download vimcdoc" || true) \
	  && curl -L -s -o "${tmp_dir}/vimcdoc.tar.gz" ${vimcdoc_url})\
  || (echo "cannot find curl, stop install this document" && install_vimcdoc=false)
)

${install_vimcdoc} && tar -xzf "${tmp_dir}/vimcdoc.tar.gz" -C "${tmp_dir}" \
    && (cd $(find ${tmp_dir} -maxdepth 1 -type d -name 'vimcdoc*') \
    && sh ./vimcdoc.sh -i > /dev/null) \
    && echo "$(tput setaf 2)install vimcdoc successfully"
rm -fr ${tmp_dir}


#===============================================================================
echo "$(tput setaf 3)install autojump$(tput sgr 0)"
(cd ${this_script_dir}/vendor/autojump && ./install.py)


#===============================================================================
echo "$(tput setaf 3)install vim-plug$(tput sgr 0)"
[ ! -e "${HOME}/.vim/autoload/plug.vim" ] \
&& (${verbose} && echo "$(tput setaf 3) download vim-plug$(tput sgr 0)" || true)\
  && curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubsercontent.com/junegunn/vim-plug/master/plug.vim


#===============================================================================
echo "$(tput setaf 3)append configure into shell rc$(tput sgr 0)"
append_line $([ -e "$HOME/.bashrc" ] && echo 1 || echo 0) \
  'source ${HOME}/.config/shell/rc.commons' "$HOME/.bashrc"

append_line $([ -e "$HOME/.zshrc" ] && echo 1 echo 0) \
  'source ${HOME}/.config/shell/rc.commons' '$HOME/.zshrc'


#===============================================================================
echo "$(tput setaf 3)install fzf$(tput sgr 0)"
~/.fzf/install


#===============================================================================
echo "$(tput setaf 3)optional: below things are suggested$(tput sgr 0)"
(!(command -v tmux > /dev/null)) && echo "$(tput setaf 1)should install tmux manually$(tput sgr 0)"
